// <auto-generated />
namespace CarParts.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class company_master_settings_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(company_master_settings_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201910281019107_company_master_settings_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
