// <auto-generated />
namespace CarParts.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_naming_convention_fixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_naming_convention_fixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201910211105401_DB_naming_convention_fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
